package com.example.spore.game.water

import androidx.compose.ui.graphics.Color
import com.example.spore.game.engine.Vector2
import kotlin.math.cos
import kotlin.math.sin
import kotlin.random.Random

/**
 * High-performance, zero-allocation water ripple and wake simulation engine.
 * Simulates:
 * - Concentric expanding water ripple waves generated by cell movements.
 * - Hydrodynamic V-shaped Kelvin wakes behind swimming organisms.
 * - Cavitation micro-bubbles and propulsion bursts.
 * - Dynamic touch perturbations when interacting with the sea.
 */
class WaterRippleSystem(
    val worldWidth: Float,
    val worldHeight: Float
) {
    companion object {
        const val MAX_RIPPLES = 48
        const val MAX_BUBBLES = 80
        const val RIPPLE_EXPANSION_SPEED = 180f
        const val RIPPLE_DECAY_RATE = 0.85f
    }

    data class WaterRipple(
        var id: Long = 0L,
        var position: Vector2 = Vector2.ZERO,
        var currentRadius: Float = 0f,
        var maxRadius: Float = 140f,
        var expansionSpeed: Float = RIPPLE_EXPANSION_SPEED,
        var amplitude: Float = 1f,
        var decayRate: Float = RIPPLE_DECAY_RATE,
        var wavelength: Float = 18f,
        var color: Color = Color(0xFF80D8FF),
        var isWake: Boolean = false,
        var wakeAngle: Float = 0f,
        var isActive: Boolean = false
    )

    data class WaterBubble(
        var position: Vector2 = Vector2.ZERO,
        var velocity: Vector2 = Vector2.ZERO,
        var radius: Float = 2f,
        var alpha: Float = 0.6f,
        var life: Float = 0f,
        var maxLife: Float = 1.2f,
        var color: Color = Color.White,
        var isActive: Boolean = false
    )

    // Pre-allocated object pools for 60fps zero-allocation performance
    val ripplePool = Array(MAX_RIPPLES) { WaterRipple() }
    val bubblePool = Array(MAX_BUBBLES) { WaterBubble() }

    private var nextRippleId = 1L
    private var swimEmitCooldown = 0f

    fun emitSwimRipple(
        position: Vector2,
        velocity: Vector2,
        cellRadius: Float,
        intensity: Float = 1f,
        color: Color = Color(0xFF80D8FF)
    ) {
        val speed = velocity.length()
        if (speed < 12f) return

        val ripple = obtainRipple() ?: return
        val angle = velocity.angle()
        // Offset slightly behind the cell to simulate propulsion wake
        val rearOffset = Vector2.fromAngle(angle + Math.PI.toFloat(), cellRadius * 0.75f)

        ripple.id = nextRippleId++
        ripple.position = position + rearOffset
        ripple.currentRadius = cellRadius * 0.4f
        ripple.maxRadius = (cellRadius * 2.8f + speed * 0.35f) * intensity
        ripple.expansionSpeed = (140f + speed * 0.5f) * intensity
        ripple.amplitude = (0.75f + (speed / 300f).coerceAtMost(0.5f)) * intensity
        ripple.decayRate = 0.95f
        ripple.wavelength = (14f + cellRadius * 0.25f)
        ripple.color = color
        ripple.isWake = true
        ripple.wakeAngle = angle
        ripple.isActive = true

        // Spawn a couple micro cavitation bubbles
        if (speed > 80f && Random.nextFloat() < 0.45f) {
            emitBubble(
                pos = position + rearOffset + Vector2(Random.nextFloat() * 10f - 5f, Random.nextFloat() * 10f - 5f),
                vel = Vector2.fromAngle(angle + Math.PI.toFloat() + (Random.nextFloat() * 0.6f - 0.3f), speed * 0.2f),
                color = color.copy(alpha = 0.7f)
            )
        }
    }

    fun emitDashShockwave(
        position: Vector2,
        cellRadius: Float,
        color: Color = Color(0xFF00E5FF)
    ) {
        // Double concentric shockwaves
        for (i in 0..1) {
            val ripple = obtainRipple() ?: break
            ripple.id = nextRippleId++
            ripple.position = position
            ripple.currentRadius = cellRadius * (0.4f + i * 0.3f)
            ripple.maxRadius = cellRadius * 4.5f
            ripple.expansionSpeed = 320f + i * 40f
            ripple.amplitude = 1.0f
            ripple.decayRate = 1.25f
            ripple.wavelength = 24f
            ripple.color = color
            ripple.isWake = false
            ripple.isActive = true
        }

        // Burst of bubbles
        for (i in 0 until 8) {
            val angle = Random.nextFloat() * 2f * Math.PI.toFloat()
            val speed = Random.nextFloat() * 90f + 40f
            emitBubble(
                pos = position + Vector2.fromAngle(angle, cellRadius * 0.5f),
                vel = Vector2.fromAngle(angle, speed),
                color = Color.White
            )
        }
    }

    fun emitTouchRipple(
        position: Vector2,
        color: Color = Color(0xFF80D8FF)
    ) {
        val ripple = obtainRipple() ?: return
        ripple.id = nextRippleId++
        ripple.position = position
        ripple.currentRadius = 8f
        ripple.maxRadius = 160f
        ripple.expansionSpeed = 200f
        ripple.amplitude = 1.0f
        ripple.decayRate = 0.8f
        ripple.wavelength = 20f
        ripple.color = color
        ripple.isWake = false
        ripple.isActive = true
    }

    fun emitBubble(pos: Vector2, vel: Vector2, color: Color = Color.White) {
        val bubble = obtainBubble() ?: return
        bubble.position = pos
        bubble.velocity = vel
        bubble.radius = Random.nextFloat() * 3.5f + 1.5f
        bubble.alpha = Random.nextFloat() * 0.4f + 0.4f
        bubble.life = 0f
        bubble.maxLife = Random.nextFloat() * 0.7f + 0.5f
        bubble.color = color
        bubble.isActive = true
    }

    private fun obtainRipple(): WaterRipple? {
        for (i in 0 until MAX_RIPPLES) {
            if (!ripplePool[i].isActive) return ripplePool[i]
        }
        // If all active, replace the oldest one with lowest amplitude
        var minAmp = Float.MAX_VALUE
        var oldestIdx = 0
        for (i in 0 until MAX_RIPPLES) {
            if (ripplePool[i].amplitude < minAmp) {
                minAmp = ripplePool[i].amplitude
                oldestIdx = i
            }
        }
        return ripplePool[oldestIdx]
    }

    private fun obtainBubble(): WaterBubble? {
        for (i in 0 until MAX_BUBBLES) {
            if (!bubblePool[i].isActive) return bubblePool[i]
        }
        return bubblePool[0]
    }

    fun update(deltaTime: Float) {
        val dt = deltaTime.coerceIn(0.005f, 0.05f)

        // Update ripples
        for (i in 0 until MAX_RIPPLES) {
            val r = ripplePool[i]
            if (!r.isActive) continue

            r.currentRadius += r.expansionSpeed * dt
            r.amplitude -= r.decayRate * dt

            if (r.amplitude <= 0.01f || r.currentRadius >= r.maxRadius) {
                r.isActive = false
            }
        }

        // Update bubbles
        for (i in 0 until MAX_BUBBLES) {
            val b = bubblePool[i]
            if (!b.isActive) continue

            b.life += dt
            b.position = b.position + (b.velocity * dt)
            b.velocity = b.velocity * 0.94f // fluid drag

            if (b.life >= b.maxLife) {
                b.isActive = false
            }
        }
    }

    fun clear() {
        for (i in 0 until MAX_RIPPLES) ripplePool[i].isActive = false
        for (i in 0 until MAX_BUBBLES) bubblePool[i].isActive = false
    }
}
